# Generated by Django 2.2.7 on 2019-11-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choices',
            options={'verbose_name': '选项', 'verbose_name_plural': '选项'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
        migrations.AlterModelTable(
            name='choices',
            table='choices',
        ),
        migrations.AlterModelTable(
            name='questions',
            table='question',
        ),
    ]
